# Making Change Without Repeats (DPV 6.18) #

### The Problem ###

We are given coin denominations $x_1, x_2 , . . . , x_n$, and we want to know if we can make change for a value $v$. 

We are allowed to use each coin denomination at most once. 

**Example:**

*Denominations: 1, 5, 10, 20* 

We can make change for $16 = 1 + 15$ and for $31 = 1 + 10 + 20$ but not for 40 because we can't use 20 twice).

### Step 1: Define subproblem in words ###

The entry $T(i, j)$ indicates whether we can make change for $j$ with the first $i$ denominations (i.e. denominations $x_1$ to $x_i$). 

### Step 2: Find the recurrence relation ###

$$
T(i, j) = \left\{\begin{aligned}
&True &&: j = x_i\\
&True &&: T(i-1,j-x_i) = True\\
&T(i-1, j) &&: otherwise
\end{aligned}
\right.
$$


### Step 3: Translate into code ###

In [23]:
import numpy as np

def coin_change_no_repeat(v, n):

    # The table T
    table = np.zeros((len(n), v), dtype=int)
    
    # For every denomination...
    for row in range(len(n)):
        # and for every value between 0 and v
        for value in range(v):
            denom = n[row]
            # If the coin denom equals the value, we can make change
            if value+1 == denom:
                table[row][value] = True
            # If we can make change for (value - denom) with previous denoms, 
            # we can make change.
            elif value-denom >= 0 and table[row-1][value-denom] == True:
                table[row][value] = True
            # If we can make change for value with previous denoms, we can make change.
            elif row > 0:
                if table[row - 1][value] == True:
                    table[row][value] = True
            # Otherwise we can't make change for value using denoms n_1, ... , n_row
            else:
                table[row][value] = False
                
    print(table)

    # The solution is the final table entry, representing whether 
    # we can make change for v using all available denominations
    solution = bool(table[-1][-1])
    print("Q. Can we make change for %d with denominations %s?" % (v, n))
    print("A. %s" % solution)
    return solution


v = 30
n = [1, 5, 10, 10, 10, 25]
coin_change_no_repeat(v=v, n=n)

v = 30
n = [25, 10, 5, 10, 10, 1]
coin_change_no_repeat(v=v, n=n)

# Test from DPV
n = [1, 5, 10, 20]
for v in (16, 31, 40):
    coin_change_no_repeat(v=v, n=n)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1]
 [1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1]]
Q. Can we make change for 30 with denominations [1, 5, 10, 10, 10, 25]?
A. True
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]
 [1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1]]
Q. Can we make change for 30 with denominations [25, 10, 5, 10, 10, 1]?
A. True
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 

### Step 4: Analyze runtime complexity ###

We loop over every value between $1$ and $v$ and we do this $n$ times. All our other operations are $O(1)$. The runtime complexity is:

$$O(nv)$$