# Max Product of String #

### The Problem: ###


The input to the problem is a string: 

$$Z=z_{1}z_{2} ... z_{n}$$ 

where each $z_{i} \in {1,2, . . . ,9}$ and an integer $k$ where $0 \le k < n$. 

An example string is $Z=8473817$, which is of length $n=7$. 

We want to insert $k$ multiplication operators ($\times$) into the string so that the mathematical result of the expression is the largest possible. There are $n - 1$ possible locations for the operators; namely, after the *i*th character where $i = 1..n−1$. 

For example, for input $Z=21322$ and $k=2$, then one possible way to insert the $\times$ operators is: 

$$2 \times 1 \times 322 = 644.$$ 

Another possibility is: 

$$21 \times 3 \times 22 = 1386.$$ 

We wish to write a dynamic programming solution to output the maximum product obtainable from inserting exactly $k$ multiplication operators into the string. We assume that all the multiplication operations in  algorithm take $O(1)$ time.

### Step 1: Define subproblem in words ###

$M(i, j) =$ maximum product obtainable from inserting exactly $i$ multiplication operations on the substring $z_{1}...z_{j}$.

### Step 2: Find the recurrence relation ###

$$
M(i, j) = \left\{\begin{aligned}
&z_{0}...z_{j} &&: i = 1\\
&\max(M(i-1, t) \times z_{t}...z_{j}) &&: i > 1, j \ge i, t \le j\\
&0 &&: otherwise
\end{aligned}
\right.
$$

### Step 3: Translate into code ###

In [23]:
import numpy as np

# This is our example string
Z = "54321"

# This is how many multiplication operators we must insert
K = 1

# It is possible to insert a maximum of |Z|-1 multiplication operators
assert K < len(Z)

# Initialize our table
M = np.zeros((len(Z), len(Z)), dtype=int)

# Iterate over rows and columns (O(n^2))
for row in range(M.shape[0]):
    for col in range(M.shape[1]):
        # We only look at cells along the main diagonal and above
        if col >= row:
            if row == 0:
                M[row, col] = int(Z[0:col+1])
            else:
                for i in range(0,col):
                    t = M[row-1, i] * int(Z[i+1:col+1])
                    if t > M[row,col]:
                        M[row,col] = t

Now we can view our completed table $M$, where each cell (i, j) contains the maximum product obtainable from inserting exactly $i$ multiplication operations on the substring $z_{1}...z_{j}$:

In [24]:
print(M)

[[    5    54   543  5432 54321]
 [    0    20   215  2160 21605]
 [    0     0    60   640  6420]
 [    0     0     0   120  1260]
 [    0     0     0     0   120]]


And our goal is to find the maximum product obtainable by inserting exactly $k$ operators into the string, so we find the max value in row $k$:

In [25]:
print(np.max(M[K]))

21605


### Step 4: Runtime Analysis ###

The input is the string $Z$, and the input size is thus $|Z|$ (the number of characters in $Z$).

Regardless of the value of $K$, we iterate over each row and column in our table $M$, which table is of dimensions $|Z|$ $\cdot$ $|Z|$. This operation is $O(n^2)$.

At the end, we iterate over each cell in row $K$, which takes $O(n)$.

The runtime is dominated by the for loop that builds the table, and therefore the algorithm's runtime is:

$$O(n^2).$$